### ISSUE TITLE
gaussian kernel

### ISSUE THREAD

**Issue by alf-ken** [JanCaha/SpatialKDE#1]
Hallo Jan,

is it possible to implement gaussian as kernelmethod? I think it is quite common and widley used.

Thanks!

**Comment by JanCaha** [comment]
Probably not a problem, if you can point me to towards specific equation that should be used.

**Comment by alf-ken** [comment]
Hi Jan, I hope this helps:

#function to calculate Gaussian kernel
gausinKernel <- function(x,b){
  K <- (1/((sqrt(2*pi))))*exp(-0.5 *(x/b)^2)
  return(K)
}
from: https://towardsdatascience.com/kernel-regression-made-easy-to-understand-86caf2d2b844

And some generall information and formulas here: http://pages.stat.wisc.edu/~mchung/teaching/MIA/reading/diffusion.gaussian.kernel.pdf.pdf

Thanks
