### ISSUE TITLE
Apply pre-made grid?

### ISSUE THREAD

**Issue by jamgreen** [JanCaha/SpatialKDE#4]
I am attempting to use the package to get kde estimates of certain land use features like bars and nuisance complaints. I have a pre-made grid the shape of my city. In trying to run the function I get the following error:

`Using centroids instead of provided `grid` geometries to calculate KDE estimates.
Error in kde_estimate(sf::st_coordinates(grid_points), sf::st_coordinates(points),  : 
  Expecting a single value: [extent=5].`

Is it strictly necessary to form a new grid for each point pattern one is looking at as opposed to applying a generalized grid? If not, what are some trouble shooting options I should make for trying to address this error?

Thank you, in advance, this is an awesome package.

**Comment by JanCaha** [comment]
It should not be necessary to create new grid. Basicaly the first part of the message tells you that centroids of the input geometry will be used to calculate KDE. Which is probably what you want. The problem starts with the `Error` ... I have no idea what might be wrong.

Does both your input `points` and `grid` have the same output from `sf::st_crs()`? Different coordinate reference system could be the cause and it can be fixed easily. Both on your side and also in the package.

If this is not the cause then I would probably need to see some example data to figure out the issue.
