### ISSUE TITLE
Using centroids instead of provided `grid` geometries

### ISSUE THREAD

**Issue by mpjashby** [JanCaha/SpatialKDE#5]
When an SF object is supplied to the `grid` argument of `kde()`, a message is printed noting "Using centroids instead of provided `grid` geometries to calculate KDE estimates". This can be seen in the documentation for the `kde()` function.

```r
[library](https://rdrr.io/r/base/library.html)([sf](https://r-spatial.github.io/sf/))
nc <- [st_read](https://r-spatial.github.io/sf/reference/st_read.html)([system.file](https://rdrr.io/r/base/system.file.html)("shape/nc.shp", package="sf")) %>% [st_transform](https://r-spatial.github.io/sf/reference/st_transform.html)(32031)
#> Reading layer `nc' from data source `/home/runner/work/_temp/Library/sf/shape/nc.shp' using driver `ESRI Shapefile'
#> Simple feature collection with 100 features and 14 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> Geodetic CRS:  NAD27
grid <- [create_grid_hexagonal](https://jancaha.github.io/SpatialKDE/reference/create_grid_rectangular.html)(nc, cell_size = 100000)
points <- [st_sample](https://r-spatial.github.io/sf/reference/st_sample.html)(nc, 500) %>% [st_as_sf](https://r-spatial.github.io/sf/reference/st_as_sf.html)()
kde_estimate_grid <- kde(points, band_width = 150000, grid = grid)
#> Using centroids instead of provided `grid` geometries to calculate KDE estimates.
```

Would it be possible to explain in a bit more detail what causes this message and in what circumstances the user should take action based on it? I _think_ it means that the function is reducing the grid squares/hexagons to their centroids and then calculating the KDE values on those centroids (effectively treating the centroids as cells in a raster layer), but it would be good to know for sure.

**Comment by JanCaha** [comment]
User effectively cannot take action based on that. It is purely informative message.
 
I believe that everyone working with KDE understands that you can not (at least not simply enough) calculate KDE for polygons. Thus the message tells user that the KDE calculation will be done on points. These are then linked back to the original geometry, so that the outcome is obtained on the same geometry that was passed into the function. No action is needed but user should know how the calculation was done.

**Comment by mpjashby** [comment]
Thanks for replying so quickly. 

I'm teaching this package to my students and I frequently get questions about this message. Since this message appears every time the `kde()` function is used on an SF object (rather than, for example, only appearing in particular circumstances), might it be better to explain that the estimation is done on centroids in the 'Details' section of the function documentation rather than by issuing a message every time the function is called? I can't think of another function that produces a message to explain how it works every time it is used, rather than putting it on the relevant man page.

If the function is to stay as it is, might it be useful to add a paragraph on the man page to explain what this message means in more detail? Or to add an optional argument `quiet = TRUE` that suppressed the message?

Thanks again!

**Comment by JanCaha** [comment]
When  version 0.7.0 is be available on CRAN, you should be able to disable this message by setting R option: 

```
options(SpatialKDE.suppres_message = TRUE)
```
I want the function to output the message most of the time as a reminder for user. I see no point in documenting it, it really should be obvious to people who want to do calculate KDE. 

Btw: A lot of functions from `sf` package will output a message every time they are run if they are doing something that user should be aware of. For example code like this:
```
library(sf)
sf_use_s2(FALSE)
nc <- st_read(system.file("shape/nc.shp", package="sf"))
st_intersects(nc, nc)
```

gives message:
```
although coordinates are longitude/latitude, st_intersects assumes that they are planar
```

**Comment by JanCaha** [comment]
When  version 0.7.0 is be available on CRAN, you should be able to disable this message by setting R option: 

```
options(SpatialKDE.suppres_message = TRUE)
```
I want the function to output the message most of the time as a reminder for user. I see no point in documenting it, it really should be obvious to people who want to do calculate KDE. 

Btw: A lot of functions from `sf` package will output a message every time they are run if they are doing something that user should be aware of. For example code like this:
```
library(sf)
sf_use_s2(FALSE)
nc <- st_read(system.file("shape/nc.shp", package="sf"))
st_intersects(nc, nc)
```

gives message:
```
although coordinates are longitude/latitude, st_intersects assumes that they are planar
```

**Comment by JanCaha** [comment]
Version 0.7.0 that allows hiding the message is available on CRAN, so I am closing this.
