### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [JanCaha/SpatialKDE#9]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

See also #6, but note that **raster** uses **terra** under the hood, so check timings with **rgdal** under **raster**, then remove **rgdal**, add **terra** and time **raster** again, before possible committing to a full upgrade.

**Comment by JanCaha** [comment]
**rgdal** was removed from Suggested. 

However, I am not going to migrate from **raster** unless absolutely necessary.

**Comment by rsbivand** [comment]
Thanks. No migration from **raster** is required, **raster** now uses **terra** in place of **rgdal** and **rgeos**.
